//! The coordinator, behind the `coordinator` capability (0007, #196, decision 0020).
//!
//! Each project has one coordinator thread: a no-write agent in wispd that plans the work, starts
//! subagents with its wisp tools (0019), and is woken when they finish. `coordinator/send` gives it
//! a message, `coordinator/cancel` stops its turn, `coordinator/get` returns the thread, and
//! `coordinator/events` pages through its events. Everything it does is also a `coordinator.*`
//! event on the project's `events/subscribe`.

use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::{CoordinatorThreadId, ProjectId, TurnId};

/// Where a coordinator thread is.
///
/// A newer wispd may send a status this version does not know; treat it as unknown.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub enum CoordinatorStatus {
    /// No turn is running. Messages and wake-ups start the next one.
    Idle,
    /// A turn's CLI is running. Messages and wake-ups wait for it to end.
    Running,
    /// A status this version does not know yet.
    #[serde(other)]
    #[ts(skip)]
    Unknown,
}

/// A project's coordinator thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CoordinatorThread {
    /// The thread's id, which the runs it starts carry as `coordinatorThread`.
    pub id: CoordinatorThreadId,
    /// Its project.
    pub project: ProjectId,
    /// Where it is.
    pub status: CoordinatorStatus,
    /// The backend its session runs on, once a turn started.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub backend: Option<String>,
    /// The account its turns are charged to, once a turn started.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub account_id: Option<String>,
    /// The vendor's session id, once a CLI reported it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub session_id: Option<String>,
    /// Why its last turn failed, for people. Absent once a turn runs again.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub error: Option<String>,
    /// When it was created, in RFC 3339 UTC.
    pub created_at: Timestamp,
    /// When it last changed, in RFC 3339 UTC.
    pub updated_at: Timestamp,
}

/// The part of a coordinator thread that changes, as `coordinator.updated` reports it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CoordinatorThreadState {
    /// Where it is.
    pub status: CoordinatorStatus,
    /// The backend its session runs on.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub backend: Option<String>,
    /// The account its turns are charged to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub account_id: Option<String>,
    /// The vendor's session id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub session_id: Option<String>,
    /// Why its last turn failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub error: Option<String>,
    /// When it changed, in RFC 3339 UTC.
    pub updated_at: Timestamp,
}

/// Params of `coordinator/get`: the project's coordinator thread, made on first use.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CoordinatorGetParams {
    /// The project.
    pub project: ProjectId,
}

/// Params of `coordinator/send`: a message to the project's coordinator.
///
/// It starts a turn at once when none is running; otherwise it waits and goes out with the next
/// turn, together with anything else that arrived meanwhile. Idempotent on `turnId` while wispd
/// runs.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CoordinatorSendParams {
    /// The project.
    pub project: ProjectId,
    /// The message's id, a version 7 UUID generated by the client.
    pub turn_id: TurnId,
    /// The message.
    pub text: String,
}

/// Params of `coordinator/cancel`: stops the coordinator's running turn, and holds back automatic
/// wake-ups until the next `coordinator/send`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CoordinatorCancelParams {
    /// The project.
    pub project: ProjectId,
}

/// Result of `coordinator/get`, `coordinator/send`, and `coordinator/cancel`: the thread as it
/// stands.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CoordinatorThreadResult {
    /// The thread.
    pub thread: CoordinatorThread,
}

/// Params of `coordinator/events`: the project's coordinator events from wispd's log, a page at a
/// time. The result is `agent/events`'s.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CoordinatorEventsParams {
    /// The project.
    pub project: ProjectId,
    /// Return the events whose `seq` is greater than this; 0 for the first page.
    pub after: u64,
    /// The most events to return: 500 by default, and at most 1000.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub limit: Option<u32>,
}
