use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::id::uuid_v7_id;
use crate::{AccountChoice, AgentEffort, AgentPermission, RunId};

uuid_v7_id! {
    /// A project's id: a version 7 UUID that the client generates once and sends again on every
    /// retry of `project/create`.
    ProjectId
}

/// A project: a body of work on one repository, run by this wispd.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    /// The id the client chose when it created the project.
    pub id: ProjectId,
    /// The name shown in the app.
    pub name: String,
    /// The absolute path of the repository on this host.
    pub repo_path: String,
    /// The branch checked out in the repository, or the first 7 digits of the commit when `HEAD`
    /// is detached, read when wispd sends the project. Absent when wispd can't read it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub branch: Option<String>,
    /// The run of the project's coordinator chat, the newest one `project/start` started (0024).
    /// Its transcript, messages, and Stop go through `agent/*` like any run's.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub coordinator: Option<RunId>,
    /// When the project was created, in RFC 3339 UTC.
    pub created_at: Timestamp,
    /// When the project last changed, in RFC 3339 UTC.
    pub updated_at: Timestamp,
}

/// Params of `project/list`.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ProjectListParams {}

/// Result of `project/list`: a snapshot of every project.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ProjectListResult {
    /// Every project, oldest first.
    pub projects: Vec<Project>,
    /// The `seq` of the last event the snapshot reflects. Subscribe with `after` set to it.
    pub seq: u64,
}

/// Params of `project/create`.
///
/// It is idempotent on `id`: if a project with that id exists, wispd returns it instead of
/// creating another, and fails with `idConflict` if `name` or `repoPath` differ. A new project's
/// `repoPath` must be the top folder of a git working tree on this host, or it fails with
/// `notARepository`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ProjectCreateParams {
    /// The new project's id, a version 7 UUID generated by the client.
    pub id: ProjectId,
    /// The name shown in the app.
    pub name: String,
    /// The absolute path of the repository on this host.
    pub repo_path: String,
}

/// Result of `project/create`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ProjectCreateResult {
    /// The project, new or existing.
    pub project: Project,
}

/// Params of `project/start`: starts the project's coordinator chat (0024), behind the
/// `coordinator` capability.
///
/// The coordinator is a run with policy `noWrite` in the project's repository, whose
/// `coordinatorThread` is its own id. Later messages, Stop, and its transcript go through
/// `agent/send`, `agent/cancel`, and `agent/events`, and its events are the project's `agent.*`
/// events. Idempotent on `runId` like `agent/start`: the same params return the run, and
/// different ones fail with `idConflict`. A project's coordinator is its newest one, which
/// `Project.coordinator` names. A new `runId` starts over: it replaces the coordinator unless that
/// one is starting or running, when it fails with `idConflict`. So a coordinator whose session
/// can't be resumed never locks its project.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ProjectStartParams {
    /// The project.
    pub project: ProjectId,
    /// The coordinator run's id, a version 7 UUID generated by the client.
    pub run_id: RunId,
    /// The user's first message.
    pub prompt: String,
    /// The account to run on. Absent means the coordinator role's default
    /// (`accounts/defaults/*`). Only a backend that can coordinate takes it: Claude Code.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub account: Option<AccountChoice>,
    /// The model, as `agent/start`'s. Absent means the CLI's default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub model: Option<String>,
    /// How hard the model thinks, as `agent/start`'s. Absent means the CLI's default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub effort: Option<AgentEffort>,
    /// The permission mode, as `agent/start`'s (RYA-188). Absent means the backend's default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub permission: Option<AgentPermission>,
}
