import {
  Activity,
  Apple,
  AppWindow,
  Archive,
  Atom,
  Bell,
  Bike,
  Blocks,
  BookOpen,
  Bookmark,
  Bot,
  Braces,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartColumn,
  ChartLine,
  ChartPie,
  Circle,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  CodeXml,
  Coffee,
  Compass,
  Component,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dices,
  Dog,
  Earth,
  Eye,
  FaceSlightlySmiling,
  Feather,
  FileCode,
  FileText,
  Film,
  FingerprintPattern,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderGit2,
  FolderKanban,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Globe,
  GraduationCap,
  Hammer,
  Hand,
  HardDrive,
  Headphones,
  Heart,
  Hexagon,
  Hourglass,
  House,
  ImageIcon,
  InfinityIcon,
  Kanban,
  Key,
  Keyboard,
  Languages,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  ListTodo,
  Lock,
  Mail,
  MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Network,
  NotebookPen,
  Orbit,
  Package,
  Palette,
  Pencil,
  PenTool,
  PiggyBank,
  Pizza,
  Plane,
  Plug,
  Puzzle,
  Rabbit,
  Rocket,
  School,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Store,
  Sun,
  Tablet,
  Tag,
  Target,
  Telescope,
  Terminal,
  ThumbsUp,
  Timer,
  TreePine,
  TrendingUp,
  Trophy,
  Type,
  User,
  Users,
  Utensils,
  Wallet,
  WandSparkles,
  WavesHorizontal,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

import type { ProjectIcon as ProjectIconValue } from "../protocol/generated/protocol";

/** One of the icons a Project can wear: its Lucide name, which plxd keeps (0032), and its glyph. */
export interface IconChoice {
  name: string;
  /** Its accessible name, from its Lucide name. */
  label: string;
  Icon: LucideIcon;
  /** Other words a search finds it by. */
  keywords: string;
}

// The picker's icons, in its order. Each is imported by name, so the bundle holds only these and
// never Lucide's whole set. A name is stored on the host, so a Lucide rename keeps the old name
// here and imports the new glyph; the test checks the old name is still Lucide's alias for it.
const icons: [name: string, Icon: LucideIcon, keywords: string][] = [
  ["folder-kanban", FolderKanban, "project board default"],
  ["folder", Folder, "directory files"],
  ["folder-git-2", FolderGit2, "repository repo"],
  ["briefcase", Briefcase, "work business job"],
  ["layers", Layers, "stack"],
  ["layout-grid", LayoutGrid, "apps tiles"],
  ["layout-dashboard", LayoutDashboard, "dashboard panels"],
  ["kanban", Kanban, "board columns tasks"],
  ["list-todo", ListTodo, "tasks checklist"],
  ["clipboard-list", ClipboardList, "tasks plan"],
  ["calendar", Calendar, "date schedule"],
  ["target", Target, "goal aim"],
  ["flag", Flag, "milestone"],
  ["bookmark", Bookmark, "saved"],
  ["tag", Tag, "label"],
  ["archive", Archive, "box storage"],
  ["package", Package, "box module npm"],
  ["blocks", Blocks, "modules pieces"],
  ["code", Code, "brackets developer"],
  ["code-xml", CodeXml, "html markup tags"],
  ["braces", Braces, "json object"],
  ["terminal", Terminal, "shell console cli"],
  ["git-branch", GitBranch, "branch version"],
  ["git-merge", GitMerge, "merge"],
  ["git-pull-request", GitPullRequest, "review pr"],
  ["bug", Bug, "issue debug insect"],
  ["cpu", Cpu, "chip processor hardware"],
  ["database", Database, "data storage sql"],
  ["server", Server, "host backend"],
  ["cloud", Cloud, "hosting"],
  ["globe", Globe, "web internet world"],
  ["network", Network, "nodes graph"],
  ["plug", Plug, "connect plugin"],
  ["puzzle", Puzzle, "plugin extension"],
  ["wrench", Wrench, "tool fix"],
  ["hammer", Hammer, "build tool"],
  ["settings", Settings, "gear cog preferences"],
  ["sliders-horizontal", SlidersHorizontal, "controls"],
  ["bot", Bot, "robot ai agent"],
  ["brain", Brain, "ai mind think"],
  ["sparkles", Sparkles, "ai magic new"],
  ["wand-sparkles", WandSparkles, "magic"],
  ["zap", Zap, "lightning fast power"],
  ["rocket", Rocket, "launch ship space"],
  ["flask-conical", FlaskConical, "lab experiment science"],
  ["atom", Atom, "science physics react"],
  ["file-code", FileCode, "source"],
  ["file-text", FileText, "document doc"],
  ["book-open", BookOpen, "docs read"],
  ["notebook-pen", NotebookPen, "notes journal"],
  ["pencil", Pencil, "edit write"],
  ["pen-tool", PenTool, "design vector"],
  ["feather", Feather, "write light"],
  ["type", Type, "text font"],
  ["languages", Languages, "translate i18n"],
  ["library", Library, "books"],
  ["palette", Palette, "design color art"],
  ["brush", Brush, "paint art"],
  ["shapes", Shapes, "shape"],
  ["component", Component, "design system"],
  ["image", ImageIcon, "picture photo"],
  ["camera", Camera, "photo"],
  ["film", Film, "video movie"],
  ["music", Music, "audio song"],
  ["headphones", Headphones, "audio listen"],
  ["mic", Mic, "microphone voice podcast"],
  ["gamepad-2", Gamepad2, "game play controller"],
  ["dices", Dices, "dice game random"],
  ["smartphone", Smartphone, "phone mobile app"],
  ["tablet", Tablet, "ipad"],
  ["laptop", Laptop, "computer"],
  ["monitor", Monitor, "screen display desktop"],
  ["keyboard", Keyboard, "type input"],
  ["app-window", AppWindow, "window app"],
  ["hard-drive", HardDrive, "disk storage"],
  ["wifi", Wifi, "network wireless"],
  ["chart-line", ChartLine, "graph analytics stats"],
  ["chart-column", ChartColumn, "graph analytics bar"],
  ["chart-pie", ChartPie, "graph"],
  ["trending-up", TrendingUp, "growth"],
  ["activity", Activity, "pulse monitor health"],
  ["gauge", Gauge, "speed performance"],
  ["timer", Timer, "stopwatch time"],
  ["clock", Clock, "time"],
  ["hourglass", Hourglass, "wait time"],
  ["bell", Bell, "notification alert"],
  ["message-square", MessageSquare, "chat comment"],
  ["messages-square", MessagesSquare, "chat conversation"],
  ["mail", Mail, "email letter"],
  ["send", Send, "paper plane"],
  ["megaphone", Megaphone, "announce marketing"],
  ["users", Users, "team people group"],
  ["user", User, "person profile"],
  ["face-slightly-smiling", FaceSlightlySmiling, "smile happy emoji"],
  ["hand", Hand, "wave hello"],
  ["thumbs-up", ThumbsUp, "like approve"],
  ["shield", Shield, "security protect"],
  ["shield-check", ShieldCheck, "secure verified"],
  ["lock", Lock, "secure private"],
  ["key", Key, "password secret auth"],
  ["fingerprint-pattern", FingerprintPattern, "fingerprint identity auth"],
  ["eye", Eye, "view watch"],
  ["search", Search, "find magnifier"],
  ["compass", Compass, "navigate explore"],
  ["map", MapIcon, "location"],
  ["map-pin", MapPin, "location place"],
  ["house", House, "home"],
  ["building", Building, "company office"],
  ["store", Store, "shop"],
  ["school", School, "education"],
  ["plane", Plane, "travel flight"],
  ["car", Car, "vehicle drive"],
  ["bike", Bike, "bicycle cycling"],
  ["shopping-cart", ShoppingCart, "cart buy commerce"],
  ["credit-card", CreditCard, "payment card"],
  ["wallet", Wallet, "money"],
  ["circle-dollar-sign", CircleDollarSign, "money finance"],
  ["piggy-bank", PiggyBank, "savings money"],
  ["gift", Gift, "present"],
  ["trophy", Trophy, "award win"],
  ["medal", Medal, "award"],
  ["crown", Crown, "king premium"],
  ["star", Star, "favorite"],
  ["heart", Heart, "love like"],
  ["gem", Gem, "jewel diamond"],
  ["lightbulb", Lightbulb, "idea"],
  ["infinity", InfinityIcon, "loop forever"],
  ["hexagon", Hexagon, "shape"],
  ["circle", Circle, "shape dot"],
  ["leaf", Leaf, "nature eco plant"],
  ["sprout", Sprout, "grow plant seed"],
  ["tree-pine", TreePine, "forest nature"],
  ["flower-2", Flower2, "plant blossom"],
  ["sun", Sun, "day light"],
  ["moon", Moon, "night dark"],
  ["flame", Flame, "fire hot"],
  ["waves-horizontal", WavesHorizontal, "waves water sea ocean"],
  ["mountain", Mountain, "hill nature"],
  ["earth", Earth, "planet world"],
  ["orbit", Orbit, "space planet"],
  ["telescope", Telescope, "space astronomy"],
  ["cat", Cat, "animal pet"],
  ["dog", Dog, "animal pet"],
  ["rabbit", Rabbit, "animal bunny"],
  ["coffee", Coffee, "drink cafe"],
  ["pizza", Pizza, "food"],
  ["apple", Apple, "fruit food"],
  ["utensils", Utensils, "food restaurant"],
  ["graduation-cap", GraduationCap, "school learn education"],
  ["ghost", Ghost, "spooky"],
];

/** "folder-git-2" reads "Folder git". */
const labelOf = (name: string) => {
  const words = name.replace(/-\d+$/, "").replaceAll("-", " ");
  return words[0]!.toUpperCase() + words.slice(1);
};

/** The icons a Project can wear, in the picker's order, the default first. */
export const projectIcons: IconChoice[] = icons.map(([name, Icon, keywords]) => ({
  name,
  label: labelOf(name),
  Icon,
  keywords,
}));
const iconsByName = new Map(projectIcons.map((i) => [i.name, i]));

/** A Project's icon until one is chosen. Picking it sends it by name, since none can't be sent. */
export const defaultIcon: ProjectIconValue = { name: "folder-kanban" };

/**
 * A color an icon can take, as Tailwind classes: the accent, which has no key, then the palette's
 * `--project-*` colors in index.css, by the key plxd keeps.
 */
export interface IconColor {
  key?: string;
  label: string;
  /** Draws a glyph in it. */
  text: string;
  /** Fills a swatch with it. */
  fill: string;
}

export const iconColors: IconColor[] = [
  { label: "Accent", text: "text-accent", fill: "bg-accent" },
  { key: "red", label: "Red", text: "text-project-red", fill: "bg-project-red" },
  { key: "orange", label: "Orange", text: "text-project-orange", fill: "bg-project-orange" },
  { key: "yellow", label: "Yellow", text: "text-project-yellow", fill: "bg-project-yellow" },
  { key: "green", label: "Green", text: "text-project-green", fill: "bg-project-green" },
  { key: "teal", label: "Teal", text: "text-project-teal", fill: "bg-project-teal" },
  { key: "sky", label: "Sky", text: "text-project-sky", fill: "bg-project-sky" },
  { key: "violet", label: "Violet", text: "text-project-violet", fill: "bg-project-violet" },
  { key: "pink", label: "Pink", text: "text-project-pink", fill: "bg-project-pink" },
  { key: "gray", label: "Gray", text: "text-project-gray", fill: "bg-project-gray" },
];
const colorsByKey = new Map(iconColors.map((c) => [c.key, c]));

/**
 * How a Project's icon draws: its glyph and its color's text class. No icon is `FolderKanban` in
 * the accent, and a name or color this app doesn't know falls back to that on its own (0032).
 */
export function iconLook(icon?: ProjectIconValue): { Icon: LucideIcon; color: string } {
  return {
    Icon: iconsByName.get(icon?.name ?? "")?.Icon ?? FolderKanban,
    color: (icon?.color && colorsByKey.get(icon.color)?.text) || "text-accent",
  };
}
